#TODO review secret/variable
api.security.token.secret=${JWT_SECRET:my-secret-key-!1@2$3Test}

#TODO update after testes
application.security.token.access-token-expiration: 60

#TODO update after testes
application.security.token.refresh-token-expiration: 120