#TODO review secret/variable
api.security.token.secret=${JWT_SECRET:my-secret-key-!1@2$3Test}

# 5 min - 5*60
application.security.token.access-token-expiration= 300
# 7 days - 7*24*60*60
application.security.token.refresh-token-expiration= 604800