#TODO review secret/variable
api.security.token.secret=${JWT_SECRET:my-secret-key-!1@2$3Test}

application.security.token.access-token-expiration= 1200

application.security.token.refresh-token-expiration= 604800